// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFnfLx4OVIYwusU7GolkFeiMZVCMmP5bQ',
    appId: '1:377097207344:web:d00c6ba09c1decc592b7f5',
    messagingSenderId: '377097207344',
    projectId: 'profondo-ai',
    authDomain: 'profondo-ai.firebaseapp.com',
    storageBucket: 'profondo-ai.firebasestorage.app',
    measurementId: 'G-FYNHTJQ4JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8riuqPo7VEBOZvcMua5skmxFwACSQm4',
    appId: '1:377097207344:android:a7c3d3c281a6285092b7f5',
    messagingSenderId: '377097207344',
    projectId: 'profondo-ai',
    storageBucket: 'profondo-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuMIIB2r71c1bNastGRBbDU6oEyziOqc',
    appId: '1:377097207344:ios:fc8da3040bbf456292b7f5',
    messagingSenderId: '377097207344',
    projectId: 'profondo-ai',
    storageBucket: 'profondo-ai.firebasestorage.app',
    iosBundleId: 'com.example.profondo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuMIIB2r71c1bNastGRBbDU6oEyziOqc',
    appId: '1:377097207344:ios:fc8da3040bbf456292b7f5',
    messagingSenderId: '377097207344',
    projectId: 'profondo-ai',
    storageBucket: 'profondo-ai.firebasestorage.app',
    iosBundleId: 'com.example.profondo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFnfLx4OVIYwusU7GolkFeiMZVCMmP5bQ',
    appId: '1:377097207344:web:693f23f4fdff879e92b7f5',
    messagingSenderId: '377097207344',
    projectId: 'profondo-ai',
    authDomain: 'profondo-ai.firebaseapp.com',
    storageBucket: 'profondo-ai.firebasestorage.app',
    measurementId: 'G-QHTZ86CT1V',
  );
}
